-- Bulk update based on verified user data
UPDATE users SET dob = '2005-10-22', leetcode_username = 'V8HjERH7Hj', leetcode_notifications_enabled = true WHERE reg_no = '25MX101';
UPDATE users SET dob = '2003-07-05', leetcode_username = 'Bala_subramaniam', leetcode_notifications_enabled = true WHERE reg_no = '25MX102';
UPDATE users SET dob = '2002-06-26', leetcode_username = 'barathvikramansk', leetcode_notifications_enabled = true WHERE reg_no = '25MX103';
UPDATE users SET dob = '2004-11-21', leetcode_username = 'DeepikaaBathirappan', leetcode_notifications_enabled = true WHERE reg_no = '25MX104';
UPDATE users SET dob = '2004-03-11', leetcode_username = 'Divya_ravi11', leetcode_notifications_enabled = true WHERE reg_no = '25MX105';
UPDATE users SET dob = '2004-04-28', leetcode_username = 'DivyadharshiniCSD', leetcode_notifications_enabled = true WHERE reg_no = '25MX106';
UPDATE users SET leetcode_username = 'Shree_Nivetha', leetcode_notifications_enabled = true WHERE reg_no = '25MX107';
UPDATE users SET dob = '2004-12-17', leetcode_username = 'Gobbika_', leetcode_notifications_enabled = true WHERE reg_no = '25MX108';
UPDATE users SET dob = '2005-01-24', leetcode_username = 'GOPINATH_R_G', leetcode_notifications_enabled = true WHERE reg_no = '25MX109';
UPDATE users SET leetcode_username = 'Harikesan', leetcode_notifications_enabled = true WHERE reg_no = '25MX110';
UPDATE users SET dob = '2004-05-09', leetcode_username = 'jarjiladenet', leetcode_notifications_enabled = true WHERE reg_no = '25MX111';
UPDATE users SET dob = '2002-09-17', leetcode_username = 'kaavya17', leetcode_notifications_enabled = true WHERE reg_no = '25MX112';
UPDATE users SET dob = '2005-04-20', leetcode_username = 'Kaleel-ur-rahman', leetcode_notifications_enabled = true WHERE reg_no = '25MX113';
UPDATE users SET dob = '2002-06-26', leetcode_username = 'kavinsde', leetcode_notifications_enabled = true WHERE reg_no = '25MX114';
UPDATE users SET dob = '2004-08-29', leetcode_username = 'krishna_priya29_', leetcode_notifications_enabled = true WHERE reg_no = '25MX115';
UPDATE users SET dob = '2005-06-13', leetcode_username = 'mirunavjn', leetcode_notifications_enabled = true WHERE reg_no = '25MX116';
UPDATE users SET leetcode_username = 'mohankumarpmj', leetcode_notifications_enabled = true WHERE reg_no = '25MX117';
UPDATE users SET dob = '2004-10-04', leetcode_username = 's_oviya', leetcode_notifications_enabled = true WHERE reg_no = '25MX118';
UPDATE users SET dob = '2003-11-03', leetcode_username = 'RemarkableCry10', leetcode_notifications_enabled = true WHERE reg_no = '25MX119';
UPDATE users SET dob = '2004-09-27', leetcode_username = 'Sibidharan27', leetcode_notifications_enabled = true WHERE reg_no = '25MX120';
UPDATE users SET dob = '2005-05-21', leetcode_username = 'SathishM29', leetcode_notifications_enabled = true WHERE reg_no = '25MX121';
UPDATE users SET dob = '2004-06-12', leetcode_username = 'shaarukesh12', leetcode_notifications_enabled = true WHERE reg_no = '25MX122';
UPDATE users SET dob = '2005-04-20', leetcode_username = 'srimonikaa', leetcode_notifications_enabled = true WHERE reg_no = '25MX123';
UPDATE users SET dob = '2005-03-09', leetcode_username = 'Srinithi_J', leetcode_notifications_enabled = true WHERE reg_no = '25MX124';
UPDATE users SET dob = '2004-08-19', leetcode_username = '477j3te85r', leetcode_notifications_enabled = true WHERE reg_no = '25MX125';
UPDATE users SET dob = '2004-12-21', leetcode_username = 's1P8DF0azg', leetcode_notifications_enabled = true WHERE reg_no = '25MX126';
UPDATE users SET dob = '2004-09-15', leetcode_username = 'SwarnaRathnaAngusamy', leetcode_notifications_enabled = true WHERE reg_no = '25MX127';
UPDATE users SET dob = '2002-11-17', leetcode_username = 'sweathaangappan', leetcode_notifications_enabled = true WHERE reg_no = '25MX128';
UPDATE users SET dob = '2003-09-02', leetcode_username = 'thiru_2903', leetcode_notifications_enabled = true WHERE reg_no = '25MX129';
UPDATE users SET dob = '2003-06-12', leetcode_username = 'Vishal_Karthikeyan_P', leetcode_notifications_enabled = true WHERE reg_no = '25MX130';
UPDATE users SET leetcode_username = 'Anu_varshini_11', leetcode_notifications_enabled = true WHERE reg_no = '25MX201';
UPDATE users SET dob = '2004-07-15', leetcode_username = 'arjun_lee', leetcode_notifications_enabled = true WHERE reg_no = '25MX202';
UPDATE users SET dob = '2004-04-11', leetcode_username = 'Badhri660', leetcode_notifications_enabled = true WHERE reg_no = '25MX203';
UPDATE users SET dob = '2004-09-17', leetcode_username = 'CHINNAYA_K', leetcode_notifications_enabled = true WHERE reg_no = '25MX204';
UPDATE users SET dob = '2004-08-22', leetcode_username = 'Deepika_200-4', leetcode_notifications_enabled = true WHERE reg_no = '25MX205';
UPDATE users SET dob = '2003-01-22', leetcode_username = 'Devibala_N', leetcode_notifications_enabled = true WHERE reg_no = '25MX206';
UPDATE users SET dob = '2004-10-25', leetcode_username = 'Dheepthi_ramakrishnan', leetcode_notifications_enabled = true WHERE reg_no = '25MX207';
UPDATE users SET leetcode_username = 'Dhina_08', leetcode_notifications_enabled = true WHERE reg_no = '25MX208';
UPDATE users SET dob = '2005-03-02', leetcode_username = 'divakar-ui', leetcode_notifications_enabled = true WHERE reg_no = '25MX209';
UPDATE users SET leetcode_username = 'Abc123abx', leetcode_notifications_enabled = true WHERE reg_no = '25MX210';
UPDATE users SET leetcode_username = 'Joshna_1304', leetcode_notifications_enabled = true WHERE reg_no = '25MX211';
UPDATE users SET dob = '2003-07-16', leetcode_username = 'Kartheesvaran', leetcode_notifications_enabled = true WHERE reg_no = '25MX212';
UPDATE users SET leetcode_username = 'Nagakeerthanaa2004', leetcode_notifications_enabled = true WHERE reg_no = '25MX214';
UPDATE users SET dob = '2005-07-13', leetcode_username = 'preethi_somu', leetcode_notifications_enabled = true WHERE reg_no = '25MX215';
UPDATE users SET dob = '2004-09-15', leetcode_username = 'Priyadharshini-Kumar', leetcode_notifications_enabled = true WHERE reg_no = '25MX216';
UPDATE users SET dob = '2004-06-23', leetcode_username = 'Mallaiah23', leetcode_notifications_enabled = true WHERE reg_no = '25MX217';
UPDATE users SET dob = '2003-03-01', leetcode_username = 'Reena_carolin', leetcode_notifications_enabled = true WHERE reg_no = '25MX218';
UPDATE users SET dob = '2004-05-17', leetcode_username = 'Saran_111', leetcode_notifications_enabled = true WHERE reg_no = '25MX219';
UPDATE users SET dob = '2004-08-06', leetcode_username = 'Sachine800', leetcode_notifications_enabled = true WHERE reg_no = '25MX220';
UPDATE users SET dob = '2005-04-08', leetcode_username = 'Shairaajvs', leetcode_notifications_enabled = true WHERE reg_no = '25MX221';
UPDATE users SET dob = '2005-05-17', leetcode_username = 'shanmugapriya17', leetcode_notifications_enabled = true WHERE reg_no = '25MX222';
UPDATE users SET dob = '2004-12-07', leetcode_username = 'Shanmugappriya_0712', leetcode_notifications_enabled = true WHERE reg_no = '25MX223';
UPDATE users SET dob = '2003-03-20', leetcode_username = 'Sriram_203', leetcode_notifications_enabled = true WHERE reg_no = '25MX224';
UPDATE users SET dob = '2004-02-18', leetcode_username = 'sriramvardaraj16', leetcode_notifications_enabled = true WHERE reg_no = '25MX225';
UPDATE users SET dob = '2005-02-21', leetcode_username = '_sudhar_sanan_', leetcode_notifications_enabled = true WHERE reg_no = '25MX226';
UPDATE users SET dob = '2002-09-24', leetcode_username = '3z9WJQnMWw', leetcode_notifications_enabled = true WHERE reg_no = '25MX227';
UPDATE users SET leetcode_username = 'supreeth_10', leetcode_notifications_enabled = true WHERE reg_no = '25MX228';
UPDATE users SET dob = '2004-10-30', leetcode_username = 'uWbraHi4Uq', leetcode_notifications_enabled = true WHERE reg_no = '25MX229';
UPDATE users SET dob = '2003-07-18', leetcode_username = 'thamizh_03', leetcode_notifications_enabled = true WHERE reg_no = '25MX230';
UPDATE users SET dob = '2005-08-27', leetcode_username = 'vaishnavis2708', leetcode_notifications_enabled = true WHERE reg_no = '25MX231';
UPDATE users SET dob = '2005-04-12', leetcode_username = 'Vishaly_Senthilkumar', leetcode_notifications_enabled = true WHERE reg_no = '25MX232';
UPDATE users SET dob = '2004-06-24', leetcode_username = '_coder_abi_', leetcode_notifications_enabled = true WHERE reg_no = '25MX301';
UPDATE users SET leetcode_username = 'aravindh245', leetcode_notifications_enabled = true WHERE reg_no = '25MX304';
UPDATE users SET dob = '2004-11-28', leetcode_username = 'bhuvishasripriya', leetcode_notifications_enabled = true WHERE reg_no = '25MX305';
UPDATE users SET leetcode_username = 'chittesh', leetcode_notifications_enabled = true WHERE reg_no = '25MX306';
UPDATE users SET leetcode_username = 'Darunya_Sri', leetcode_notifications_enabled = true WHERE reg_no = '25MX307';
UPDATE users SET leetcode_username = 'DayanandaJ', leetcode_notifications_enabled = true WHERE reg_no = '25MX308';
UPDATE users SET dob = '2004-01-18', leetcode_username = 'PPuHO8lVwI', leetcode_notifications_enabled = true WHERE reg_no = '25MX309';
UPDATE users SET dob = '2004-04-28', leetcode_username = 'Dhakshanamoorthy', leetcode_notifications_enabled = true WHERE reg_no = '25MX310';
UPDATE users SET leetcode_username = 'Dinesh_rrr', leetcode_notifications_enabled = true WHERE reg_no = '25MX312';
UPDATE users SET dob = '2004-04-20', leetcode_username = 'lalitchandran2004', leetcode_notifications_enabled = true WHERE reg_no = '25MX313';
UPDATE users SET dob = '2003-05-22', leetcode_username = 'HariBalaji', leetcode_notifications_enabled = true WHERE reg_no = '25MX314';
UPDATE users SET leetcode_username = 'indujaee', leetcode_notifications_enabled = true WHERE reg_no = '25MX315';
UPDATE users SET dob = '2003-08-07', leetcode_username = 'naanthandaleo', leetcode_notifications_enabled = true WHERE reg_no = '25MX316';
UPDATE users SET leetcode_username = 'u00mGgJrMX', leetcode_notifications_enabled = true WHERE reg_no = '25MX317';
UPDATE users SET dob = '2004-05-20', leetcode_username = 'jeevasilviya', leetcode_notifications_enabled = true WHERE reg_no = '25MX318';
UPDATE users SET dob = '2004-12-09', leetcode_username = 'Jessica96', leetcode_notifications_enabled = true WHERE reg_no = '25MX319';
UPDATE users SET dob = '2004-07-04', leetcode_username = 'joshnie47', leetcode_notifications_enabled = true WHERE reg_no = '25MX320';
UPDATE users SET dob = '2004-10-05', leetcode_username = 'Karthick0531', leetcode_notifications_enabled = true WHERE reg_no = '25MX321';
UPDATE users SET dob = '2005-04-04', leetcode_username = 'kasbiya_l', leetcode_notifications_enabled = true WHERE reg_no = '25MX322';
UPDATE users SET dob = '2005-05-29', leetcode_username = 'Kize_Bright', leetcode_notifications_enabled = true WHERE reg_no = '25MX323';
UPDATE users SET leetcode_username = 'Kevin_0104', leetcode_notifications_enabled = true WHERE reg_no = '25MX324';
UPDATE users SET dob = '2004-08-27', leetcode_username = 'ClyHz34SHz', leetcode_notifications_enabled = true WHERE reg_no = '25MX325';
UPDATE users SET leetcode_username = 'Meyappan_R', leetcode_notifications_enabled = true WHERE reg_no = '25MX326';
UPDATE users SET dob = '2004-09-13', leetcode_username = 'im_mithra', leetcode_notifications_enabled = true WHERE reg_no = '25MX327';
UPDATE users SET leetcode_username = 'Mithulesh_N', leetcode_notifications_enabled = true WHERE reg_no = '25MX328';
UPDATE users SET dob = '2004-07-19', leetcode_username = 'mohanapriya19', leetcode_notifications_enabled = true WHERE reg_no = '25MX329';
UPDATE users SET leetcode_username = '9AIYYQsbfu', leetcode_notifications_enabled = true WHERE reg_no = '25MX330';
UPDATE users SET leetcode_username = 'Mukunth06', leetcode_notifications_enabled = true WHERE reg_no = '25MX331';
UPDATE users SET leetcode_username = 'muthusailappan', leetcode_notifications_enabled = true WHERE reg_no = '25MX332';
UPDATE users SET dob = '2004-08-20', leetcode_username = 'Nagasruthimanivannan', leetcode_notifications_enabled = true WHERE reg_no = '25MX333';
UPDATE users SET leetcode_username = 'nandhithasri315', leetcode_notifications_enabled = true WHERE reg_no = '25MX334';
UPDATE users SET leetcode_username = 'Naveenpranab', leetcode_notifications_enabled = true WHERE reg_no = '25MX335';
UPDATE users SET dob = '2005-07-05', leetcode_username = 'nitheeshmk5', leetcode_notifications_enabled = true WHERE reg_no = '25MX336';
UPDATE users SET leetcode_username = 'Nithyashree_C', leetcode_notifications_enabled = true WHERE reg_no = '25MX337';
UPDATE users SET dob = '2005-03-24', leetcode_username = 'PooraniMohan24', leetcode_notifications_enabled = true WHERE reg_no = '25MX338';
UPDATE users SET dob = '2004-11-08', leetcode_username = 'prabha6769', leetcode_notifications_enabled = true WHERE reg_no = '25MX339';
UPDATE users SET dob = '2004-10-29', leetcode_username = 'Puratchiyan', leetcode_notifications_enabled = true WHERE reg_no = '25MX340';
UPDATE users SET dob = '2005-01-06', leetcode_username = 'fkenq9S0hw', leetcode_notifications_enabled = true WHERE reg_no = '25MX341';
UPDATE users SET dob = '2005-05-21', leetcode_username = 'Mahesh__rdr', leetcode_notifications_enabled = true WHERE reg_no = '25MX342';
UPDATE users SET leetcode_username = 'SABARISH_P', leetcode_notifications_enabled = true WHERE reg_no = '25MX343';
UPDATE users SET leetcode_username = 'SATYA_PRAMODH', leetcode_notifications_enabled = true WHERE reg_no = '25MX344';
UPDATE users SET dob = '2005-07-26', leetcode_username = 'M_Shri_sanjay26', leetcode_notifications_enabled = true WHERE reg_no = '25MX345';
UPDATE users SET leetcode_username = 'sidddarthvasi2604', leetcode_notifications_enabled = true WHERE reg_no = '25MX346';
UPDATE users SET leetcode_username = 'Sivapradeesh_M', leetcode_notifications_enabled = true WHERE reg_no = '25MX347';
UPDATE users SET dob = '2001-12-21', leetcode_username = 'sobanss2001', leetcode_notifications_enabled = true WHERE reg_no = '25MX348';
UPDATE users SET dob = '2003-03-03', leetcode_username = 'sowmiya_3', leetcode_notifications_enabled = true WHERE reg_no = '25MX349';
UPDATE users SET dob = '2004-09-06', leetcode_username = 'SRIVIKASHNI', leetcode_notifications_enabled = true WHERE reg_no = '25MX350';
UPDATE users SET leetcode_username = 'suriyaCSD', leetcode_notifications_enabled = true WHERE reg_no = '25MX351';
UPDATE users SET dob = '2004-10-29', leetcode_username = 'oi8UIWVPvT', leetcode_notifications_enabled = true WHERE reg_no = '25MX352';
UPDATE users SET leetcode_username = 'Thrishaa123', leetcode_notifications_enabled = true WHERE reg_no = '25MX353';
UPDATE users SET dob = '2004-07-08', leetcode_username = 'tinobritty', leetcode_notifications_enabled = true WHERE reg_no = '25MX354';
UPDATE users SET dob = '2005-01-02', leetcode_username = '__Vaishu_7__', leetcode_notifications_enabled = true WHERE reg_no = '25MX355';
UPDATE users SET dob = '2004-01-31', leetcode_username = 'Vix-codes', leetcode_notifications_enabled = true WHERE reg_no = '25MX356';
UPDATE users SET leetcode_username = '12_zoya', leetcode_notifications_enabled = true WHERE reg_no = '25MX357';
UPDATE users SET dob = '2004-11-17', leetcode_username = 'lemonspice17', leetcode_notifications_enabled = true WHERE reg_no = '25MX358';
UPDATE users SET dob = '2004-12-24', leetcode_username = 'vishnuvardani_2004', leetcode_notifications_enabled = true WHERE reg_no = '25MX359';
UPDATE users SET dob = '2004-07-01', leetcode_username = 'yash_3237', leetcode_notifications_enabled = true WHERE reg_no = '25MX360';
UPDATE users SET dob = '2004-04-29', leetcode_username = 'sanjana_m29', leetcode_notifications_enabled = true WHERE reg_no = '25MX361';
UPDATE users SET leetcode_username = 'Narayana_1080', leetcode_notifications_enabled = true WHERE reg_no = '25MX362';
UPDATE users SET dob = '2003-04-12', leetcode_username = 'Tectonic_', leetcode_notifications_enabled = true WHERE reg_no = '25MX363';
